/*
  __
 /\ \
 \_\ \    ____  __  __     __
 /'_` \  /',__\/\ \/\ \  /'__`\
/\ \L\ \/\__, `\ \ \_/ |/\  __/
\ \___,_\/\____/\ \___/ \ \____\
 \/__,_ /\/___/  \/__/   \/____/

*/

USE dsve_cinema_booking_system;

SHOW TABLES;

DESCRIBE customers;

SELECT * FROM customers;

INSERT INTO customers (customerFirstName, customerLastName, customerEmail, customerGender)
VALUES ('David', 'May', 'dmay@gmail.com', 'M'),
       ('Theresa', 'Davis', 'tdavis@gmail.com', 'F'),
       ('Jerry', 'Martin', 'jermar@gmail.com', 'M'),
       ('John', 'Smith', 'smithy@gmail.com', 'M'),
       ('Martin', 'Watkins', 'mwatto@gmail.com', 'M'),
       ('Emma', 'Watson', 'itswingardiumleviosa@gmail.com', 'F'),
       ('Javier', 'Pastore', 'jp@gmail.com', 'M'),
       ('Charlotte', 'Hare', 'chare@gmail.com', 'F'),
       ('Mark', 'Smith', 'markysmith@gmail.com', 'M'),
       ('Emily', 'Thorne', 'ethorne@gmail.com', 'F'),
       ('David', 'Paul', 'davpaul@gmail.com', 'M'),
       ('Cherry', 'Wang', 'cherryw@gmail.com', 'F'),
       ('Bort', 'Simpson', 'mynameisbort@gmail.com', 'M'),
       ('Emma', 'Connor', 'econ@gmail.com', 'F'),
       ('Jonathan', 'Edwards', 'jedwards@gmail.com', 'M'),
       ('Simon', 'Davis', 'sdavis@gmail.com', 'M'),
       ('Sophie', 'Marshall', 'sophmarsh@gmail.com', 'F'),
       ('Sally', 'Lam', 'slam@gmail.com', 'F'),
       ('Kenneth', 'Harrison', 'kson@gmail.com', 'M'),
       (NULL, 'Smith', 'smith@gmail.com', 'F'),
       ('Harry', 'Weasley', 'whatsmyname@gmail.com', 'M'),
       ('Ron', 'Potter', 'thatsmyname@gmail.com', 'M'),
       ('Ray', 'Wilkinson', 'wilky@gmail.com', 'M'),
       ('Samuel', 'Windsor', 'royalty@gmail.com', 'M'),
       ('Jennifer', 'David', 'jda@gmail.com', 'F'),
       ('Larry', 'Davis', 'larryd@gmail.com', 'M'),
       ('Bolt', 'Tin', 'btin@gmail.com', 'M'),
       ('Sarah', 'Thompson', 'sthompson1977@gmail.com', 'F'),
       ('Alan', 'Bennet', 'thosewerethedays@gmail.com', 'M'),
       ('Brian', 'Apple', 'bapple101@gmail.com', 'M'),
       ('Rob', 'Bryson', 'rbry@gmail.com', 'M'),
       ('Shelly', 'Zu', 'szu@gmail.com', 'F'),
       ('Steve', 'Shoogan', 'sshoogan@gmail.com', 'M'),
       ('Matthew', 'Gray', 'graym@gmail.com', 'M'),
       ('Sally', 'Kramer', 'kallysramer@gmail.com', 'F'),
       ('Peter', 'Chef', 'chefp@gmail.com', 'M'),
       (NULL, 'Cooke', 'nullcooke@gmail.com', 'F'),
       ('Marty', 'Seinfeld', 'marfeld@gmail.com', 'M'),
       ('Carl', 'Green', 'creen@gmail.com', 'M'),
       ('Emma', 'Greene', 'egreene@gmail.com', 'F'),
       ('Michael', 'Bannon', 'mbannon@gmail.com', 'M'),
       ('Paul', 'Showman', 'theshowman1@gmail.com', 'M'),
       ('Harry', 'Goldthistle', 'hgold@gmail.com', 'M'),
       ('Gill', 'Newton', 'gnew@gmail.com', 'F'),
       ('Preston', 'Peters', 'p2p@gmail.com', 'M'),
       ('Simon', 'Smithson', 'sismithson@gmail.com', 'M'),
       ('Benjamin', 'Rabbit', 'brabbit@gmail.com', 'M'),
       ('Jerry', 'David', 'curb@gmail.com', 'M'),
       ('Olivia', 'Tulip', 'otulip@gmail.com', 'F'),
       ('Richard', 'Horne', 'richhorne@gmail.com', 'M'),
       ('Betty', 'Corbe', 'bcorbe@gmail.com', 'F'),
       ('Anne', 'Callaway', 'acway@gmail.com', 'F'),
       ('Yifan', 'Way', 'yway@gmail.com', 'F'),
       ('Charlie', 'Cheene', 'ccheene@gmail.com', 'M'),
       ('Ula', 'Boon', 'uboon@gmail.com', 'F'),
       ('Buster', 'David', 'bdavid@gmail.com', 'M'),
       ('Dustin', 'Beer', 'beerd@gmail.com', 'F'),
       ('John', 'Sleet', 'knoweverything@gmail.com', 'F'),
       ('August', 'Summer', 'asummer@gmail.com', 'M'),
       ('Linda', 'Martins', 'lmart@gmail.com', 'F'),
       ('Chris', 'Kay', 'chkay@gmail.com', 'M'),
       ('Christopher', 'Roberts', 'croberts@gmail.com', 'M'),
       ('Robert', 'Winston', 'rwin@gmail.com', 'M'),
       ('Daniel', 'Orbe', 'dorbe@gmail.com', 'M'),
       ('Joshua', 'Wells', 'wellj@gmail.com', 'F'),
       ('Fred', 'Flinton', 'ff100@gmail.com', 'M'),
       ('Paula', 'Winner', 'pwinner@gmail.com', 'F'),
       (NULL, 'Canter', 'canter99@gmail.com', 'F'),
       ('Michael', 'Bassett', 'mbass@gmail.com', 'M'),
       ('Michelle', 'Martins', 'mm109@gmail.com', 'F'),
       ('Lorna', 'Brown', 'lbrown@gmail.com', 'F'),
       ('Kerry', 'Vale', 'wish1985@gmail.com', 'M'),
       ('Sean', 'Borne', 'sborne@gmail.com', 'M'),
       ('Craig', 'Evans', 'cevans@gmail.com', 'M'),
       ('Alex', 'Sanders', 'asand@gmail.com', 'F'),
       ('George', 'McNabb', 'gnabb@gmail.com', 'M'),
       ('Richard', 'Trout', 'redtrout@gmail.com', 'M'),
       ('Stewart', 'Dee', 'sdee@gmail.com', 'M'),
       ('Sue', 'Werkins', 'swerkins@gmail.com', 'F'),
       ('Mel', 'Wozniack', 'mwoz@gmail.com', 'F'),
       ('Steve', 'Dole', 'sdole@gmail.com', 'M'),
       ('Zara', 'Yelland', 'zy27@gmail.com', 'F'),
       ('Irene', 'Mellon', 'mellonirene@gmail.com', 'F'),
       ('Karen', 'Wall', 'kwall@gmail.com', 'F'),
       ('Lucy', 'Oak', 'loak@gmail.com', 'F'),
       ('Orson', 'Young', 'oyoung@gmail.com', 'M'),
       ('Oliver', 'Daniels', 'odaniels@gmail.com', 'M'),
       ('Queen', 'Bee', 'qbee@gmail.com', 'F'),
       ('Vera', 'Jack', 'verajack@gmail.com', 'F'),
       ('Thomas', 'Soft', 'softt@gmail.com', 'M'),
       (NULL, 'Blair', 'nblair@gmail.com', 'F'),
       ('Tim', 'Jones', 'tjones@gmail.com', 'M'),
       ('Nicola', 'Jenkins', 'njenk@gmail.com', 'F'),
       ('Olivia', 'Jones', 'ojo@gmail.com', 'F'),
       ('James', 'Depp', 'jdepp@gmail.com', 'M'),
       ('Meryl', 'Steep', 'msteep@gmail.com', 'F'),
       ('Jake', 'Portman', 'jportman@gmail.com', 'M'),
       ('Jenny', 'Appleton', 'japple@gmail.com', 'F'),
       ('Simon', 'Hoover', 'shoover@gmail.com', 'M'),
       ('Belinda', 'Marshall', 'belindam@gmail.com', 'F'),
       ('Stephanie', 'Watson', 'swatson@gmail.com', 'F'),
       ('Art', 'Simons', 'simons@gmail.com', 'M'),
       ('Stan', 'Smith', 'smithstan@gmail.com', 'M'),
       ('Christopher', 'Roberts', 'robertsc@gmail.com', 'M'),
       ('Nathan', 'Gold', 'engold@gmail.com', 'M'),
       ('Alain', 'Bennet', 'alainb@gmail.com', 'M'),
       ('Lewis', 'Russelton', 'lrus@gmail.com', 'M'),
       ('Josh', 'Reynolds', 'jrey@gmail.com', 'M'),
       ('William', 'Williams', 'williamw@gmail.com', 'M'),
       (NULL, 'Pointer', 'apointer@gmail.com', 'M'),
       ('Bort', 'Skinner', 'mynameisalsobort@gmail.com', 'M'),
       (NULL, 'Smith', 'lonsmith@gmail.com', 'M'),
       ('Susan', 'Williams', 'swill@gmail.com', 'F'),
       ('Yu', 'Xi', 'yuxi@gmail.com', 'F'),
       ('Annabelle', 'Winks', 'anwinks@gmail.com', 'F'),
       ('Andrew', 'Landhurst', 'andylandy@gmail.com', 'M'),
       ('Winston', 'Smith', 'room101@gmail.com', 'M'),
       ('Gemma', 'Arton', 'garton@gmail.com', 'F'),
       ('Renton', 'McDonald', 'rent@gmail.com', 'M'),
       ('Maggie', 'Chu', 'chuchu@gmail.com', 'F');

SELECT *
FROM customers;

SELECT *
FROM customers
ORDER BY customerLastName;